# Generated by Django 2.0.1 on 2021-08-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('interested_company', models.CharField(max_length=30)),
                ('interested_job', models.CharField(blank=True, max_length=30, null=True)),
                ('mentor_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=30)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('initial_num_mentee', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
